-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_MFA_RESET';

-- AlterTable
ALTER TABLE "AdminUser" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;
